version: '3.7'
services:
  flask-app:
    build: ./flask-app
    image: flask-app
    deploy:
      replicas: 4
    environment:
      DB_PASS: pass
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  database:
    build: ./db
    image: db
    deploy:
      replicas: 4
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - target: 3306
      published: 3306
  nginx:
    image: nginx:latest
    deploy:
      replicas: 4
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
